---
title: "Final Project"
author: "Blain Morin"
date: "December 17, 2018"
output: pdf_document
header-includes:
- \usepackage{float}
---

```{r, echo = FALSE, message = FALSE, warning = FALSE}

### Set knitr options
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

### Load Required Libraries

library(readr)
library(dplyr)
library(ggplot2)
library(extrafont)

### Load Data
full = read_delim("2010_6.csv", "\t", 
                      escape_double = FALSE, trim_ws = TRUE)

```

```{r}

### Get smaller data
full = full %>%
  filter(a > 1,
         b > 1,
         c > 1,
         d > 1) %>%
  group_by(my_ID) %>%
  mutate(correct_no_of_studies = n()) %>%
  ungroup() %>%
  filter(correct_no_of_studies >= 5) 


### Get only largest meta (highest number of studies)
full = full %>%
  group_by(number_review) %>%
  filter(correct_no_of_studies == max(correct_no_of_studies)) %>%
  mutate(n = a + b + c + d) %>%
  group_by(my_ID) %>%
  mutate(meta.n = sum(n)) %>%
  ungroup() %>%
  group_by(number_review) %>%
  filter(meta.n == max(meta.n)) %>%
  ungroup()


```

```{r}

### Add study effect size and variance
### Add DesSimonian-Laird Estimate for tau2 and se.tau2
full = full %>% 
  mutate(yi = escalc(measure = "OR",
                     ai = a,
                     bi = b,
                     ci = c, 
                     di = d)$yi,
         vi = escalc(measure = "OR",
                     ai = a,
                     bi = b,
                     ci = c, 
                     di = d)$vi) %>%
  group_by(my_ID) %>%
  mutate(DL.tau2 = rma.uni(yi = yi,
                           vi = vi,
                           method = "DL")$tau2,
         DL.se.tau2 = rma.uni(yi = yi,
                           vi = vi,
                           method = "DL")$se.tau2,
         DL.summary = rma.uni(yi = yi,
                           vi = vi,
                           method = "DL")$beta) %>%
  ungroup()
  


```

```{r}

### Add Paule and Mandel 
full = full %>%
  group_by(my_ID) %>%
  mutate(PM.tau2 = rma.uni(yi = yi,
                           vi = vi,
                           method = "PM")$tau2,
         PM.se.tau2 = rma.uni(yi = yi,
                           vi = vi,
                           method = "PM")$se.tau2,
         PM.summary = rma.uni(yi = yi,
                           vi = vi,
                           method = "PM")$beta) %>%
  ungroup()
  

```

```{r}

### Add Hedges 
full = full %>%
  group_by(my_ID) %>%
  mutate(HE.tau2 = rma.uni(yi = yi,
                           vi = vi,
                           method = "HE")$tau2,
         HE.se.tau2 = rma.uni(yi = yi,
                           vi = vi,
                           method = "HE")$se.tau2,
         HE.summary = rma.uni(yi = yi,
                           vi = vi,
                           method = "HE")$beta) %>%
  ungroup()

```

```{r}

### Add Hunter-Schmidt
full = full %>%
  group_by(my_ID) %>%
  mutate(HS.tau2 = rma.uni(yi = yi,
                           vi = vi,
                           method = "HS")$tau2,
         HS.se.tau2 = rma.uni(yi = yi,
                           vi = vi,
                           method = "HS")$se.tau2,
         HS.summary = rma.uni(yi = yi,
                           vi = vi,
                           method = "HS")$beta) %>%
  ungroup()

```

```{r}

### Add Maximum Likelihood
full = full %>%
  group_by(my_ID) %>%
  mutate(ML.tau2 = rma.uni(yi = yi,
                           vi = vi,
                           method = "ML")$tau2,
         ML.se.tau2 = rma.uni(yi = yi,
                           vi = vi,
                           method = "ML")$se.tau2,
         ML.summary = rma.uni(yi = yi,
                           vi = vi,
                           method = "ML")$beta) %>%
  ungroup()

```

```{r}

### Add REML
full = full %>%
  group_by(my_ID) %>%
  mutate(REML.tau2 = rma.uni(yi = yi,
                           vi = vi,
                           method = "REML", control=list(maxiter=1000))$tau2,
         REML.se.tau2 = rma.uni(yi = yi,
                           vi = vi,
                           method = "REML", control=list(maxiter=1000))$se.tau2,
         REML.summary = rma.uni(yi = yi,
                           vi = vi,
                           method = "REML", control=list(maxiter=1000))$beta) %>%
  ungroup()

```

```{r}

### Add Sidik-Jonkman
full = full %>%
  group_by(my_ID) %>%
  mutate(SJ.tau2 = rma.uni(yi = yi,
                           vi = vi,
                           method = "SJ")$tau2,
         SJ.se.tau2 = rma.uni(yi = yi,
                           vi = vi,
                           method = "SJ")$se.tau2,
         SJ.summary = rma.uni(yi = yi,
                           vi = vi,
                           method = "SJ")$beta) %>%
  ungroup()


```





```{r, fig.width=12}

set.seed(100)
full %>%
  group_by(number_review) %>%
  slice(1) %>%
  ungroup() %>%
  sample_n(size = 60) %>%
  ggplot(aes(x = review)) +
  geom_point(aes(y = PM.tau2), color = "red", shape = 15, size = 3) +
  geom_point(aes(y = DL.tau2), color = "green", shape = 15, size = 3) +
  geom_point(aes(y = SJ.tau2), color = "blue", shape = 15, size = 3) +
  geom_point(aes(y = HE.tau2), color = "yellow", shape = 15, size = 3) +
  geom_point(aes(y = HS.tau2), color = "purple", shape = 15, size = 3) +
  geom_point(aes(y = ML.tau2), color = "orange", shape = 15, size = 3) +
  geom_point(aes(y = REML.tau2), color = "black", shape = 15, size = 3) +
  theme_light() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  ylab("Tau Squared") +
  xlab("Cochrane Review") +
  theme(text=element_text(size=12,  family="CM Sans"))
  

```


```{r}



```




